version: 2.0

aliases:

  node10: &node10image
    docker:
      - image: circleci/node:10

  node9: &node9image
    docker:
      - image: circleci/node:9

  node8: &node8image
    docker:
      - image: circleci/node:8

  install_npm_default: &install_npm
    run: 
      name: Update npm
      command: 'sudo npm install -g npm@latest'
  restore_cache_default: &restore_cache # special step to restore the dependency cache
    restore_cache:
        # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
        key: dependency-cache-{{ checksum "package.json" }}
  install_npm_packages_default: &install_npm_packages
    run:
        name: Install npm packages
        command: npm install
  save_cache_default: &save_cache # special step to save the dependency cache
    save_cache: 
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
    
jobs:

  # Lint and Test
  # this fails on node 6 and 7 and works on 8 onwards

  lint_and_test_node_11: &lint_and_test
    docker:
      - image: circleci/node:11
    steps: 
      - checkout
      - *install_npm
      - *restore_cache
      - *install_npm_packages
      - *save_cache
      - run: &lint
          name: Lint
          command: npm run shim:lint
      - run: &build
          name: Build
          command: npm run shim:build
      - run: &test 
          name: Test
          command: npm run shim:test
      - run: &test_integration
          name: Test-Integration
          command: npm run shim:test-integration 

  lint_and_test_node_10:
    <<: *lint_and_test
    <<: *node10image
      
  lint_and_test_node_9:
    <<: *lint_and_test
    <<: *node9image

  lint_and_test_node_8:
    <<: *lint_and_test
    <<: *node8image

workflows:
  version: 2
  test_all:
    jobs:
      - lint_and_test_node_11
      - lint_and_test_node_10
      - lint_and_test_node_9
      - lint_and_test_node_8
